# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 09:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0171_auto_20190219_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('initial', 'Initial'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='initial', help_text='initial - Initial,accepted - Accepted,rejected - Rejected', max_length=20),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[('initial', 'Initial'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('declined', 'Declined'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='initial', help_text='initial - Initial, submitted - Submitted, approved - Approved, declined - Declined, accepted - Accepted, rejected - Rejected', max_length=20),
        ),
        migrations.AlterField(
            model_name='integration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integrations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='integration',
            name='provider',
            field=models.CharField(choices=[('github', 'GitHub'), ('slack', 'Slack'), ('harvest', 'Harvest')], help_text='github - GitHub,slack - Slack,harvest - Harvest', max_length=30),
        ),
        migrations.AlterField(
            model_name='integrationactivity',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_activities', to='tunga_tasks.IntegrationEvent'),
        ),
        migrations.AlterField(
            model_name='multitaskpaymentkey',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD')], default='EUR', max_length=5),
        ),
        migrations.AlterField(
            model_name='multitaskpaymentkey',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('ayden', 'Pay with Ayden'), ('stripe', 'Pay with Stripe'), ('bitonic', 'Pay with iDeal / mister cash'), ('bitcoin', 'Pay with BitCoin'), ('bank', 'Pay by bank transfer')], help_text='ayden - Pay with Ayden,stripe - Pay with Stripe,bitonic - Pay with iDeal / mister cash,bitcoin - Pay with BitCoin,bank - Pay by bank transfer', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='participantpayment',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tunga_tasks.Participation'),
        ),
        migrations.AlterField(
            model_name='participantpayment',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tunga_tasks.TaskPayment'),
        ),
        migrations.AlterField(
            model_name='participantpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('retry', 'Retry')], default='pending', help_text='pending - Pending, initiated - Initiated, processing - Processing, completed - Completed, failed - Failed, canceled - Canceled, retry - Retry', max_length=30),
        ),
        migrations.AlterField(
            model_name='participation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('initial', 'Initial'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='initial', help_text='initial - Initial,accepted - Accepted,rejected - Rejected', max_length=20),
        ),
        migrations.AlterField(
            model_name='progressevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_progress_events_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('initial', 'Initial'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('declined', 'Declined'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='initial', help_text='initial - Initial, submitted - Submitted, approved - Approved, declined - Declined, accepted - Accepted, rejected - Rejected', max_length=20),
        ),
        migrations.AlterField(
            model_name='skillsapproval',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tunga_tasks.Participation'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('initial', 'Initial'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('declined', 'Declined'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='initial', help_text='initial - Initial, submitted - Submitted, approved - Approved, declined - Declined, accepted - Accepted, rejected - Rejected', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('ayden', 'Pay with Ayden'), ('stripe', 'Pay with Stripe'), ('bitonic', 'Pay with iDeal / mister cash'), ('bitcoin', 'Pay with BitCoin'), ('bank', 'Pay by bank transfer')], help_text='ayden - Pay with Ayden,stripe - Pay with Stripe,bitonic - Pay with iDeal / mister cash,bitcoin - Pay with BitCoin,bank - Pay by bank transfer', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='skills',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', initial='PHP, JavaScript, Python, Ruby, Java, C#, C++, Ruby, Swift, Objective C, .NET, ASP.NET, Node.js,HTML, CSS, HTML5, CSS3, XML, JSON, YAML,Django, Ruby on Rails, Flask, Yii, Lavarel, Express.js, Spring, JAX-RS,AngularJS, React.js, Meteor.js, Ember.js, Backbone.js,WordPress, Joomla, Drupal,jQuery, jQuery UI, Bootstrap, AJAX,Android, iOS, Windows Mobile, Apache Cordova, Ionic,SQL, MySQL, PostgreSQL, MongoDB, CouchDB,Git, Subversion, Mercurial, Docker, Ansible, Webpack, Grunt, Gulp, Ant, Maven, Gradle', space_delimiter=False, to='tunga_profiles.Skill'),
        ),
        migrations.AlterField(
            model_name='taskdocument',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskdocument',
            name='file_type',
            field=models.CharField(choices=[('estimate', 'Estimate'), ('proposal', 'Proposal'), ('planning', 'Planning'), ('requirements', 'Requirements Document'), ('wireframes', 'Wireframes'), ('timeline', 'Timeline'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='taskdocument',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tunga_tasks.Task'),
        ),
        migrations.AlterField(
            model_name='taskinvoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskinvoice',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='developer_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskinvoice',
            name='payment_method',
            field=models.CharField(choices=[('ayden', 'Pay with Ayden'), ('stripe', 'Pay with Stripe'), ('bitonic', 'Pay with iDeal / mister cash'), ('bitcoin', 'Pay with BitCoin'), ('bank', 'Pay by bank transfer')], help_text='ayden - Pay with Ayden,stripe - Pay with Stripe,bitonic - Pay with iDeal / mister cash,bitcoin - Pay with BitCoin,bank - Pay by bank transfer', max_length=30),
        ),
        migrations.AlterField(
            model_name='taskinvoice',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tunga_tasks.Task'),
        ),
        migrations.AlterField(
            model_name='taskpayment',
            name='currency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR'), ('USD', 'USD')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='taskpayment',
            name='multi_pay_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tunga_tasks.MultiTaskPaymentKey'),
        ),
        migrations.AlterField(
            model_name='taskpayment',
            name='payment_type',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('bitcoin', 'BitCoin'), ('bank', 'Bank Transfer'), ('payoneer', 'Payoneer')], help_text='stripe - Stripe,bitcoin - BitCoin,bank - Bank Transfer,payoneer - Payoneer', max_length=30),
        ),
        migrations.AlterField(
            model_name='taskpayment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tunga_tasks.Task'),
        ),
    ]
