# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 09:14
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_auth', '0021_tungauser_can_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tungauser',
            name='payoneer_status',
            field=models.CharField(choices=[('initial', 'Initial'), ('initiated', 'Initiated'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Decline')], default='initial', help_text='initial - Initial, initiated - Initiated, pending - Pending, approved - Approved, declined - Decline', max_length=20),
        ),
        migrations.AlterField(
            model_name='tungauser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
