# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-26 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_auth', '0022_auto_20190527_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='tungauser',
            name='present_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tungauser',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
