# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 09:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_support', '0005_auto_20160801_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportpage',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_pages_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportsection',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_sections_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
