# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_activity', '0004_auto_20180912_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationreadlog',
            name='type',
            field=models.CharField(choices=[('profile', 'Profile'), ('activity', 'Activity')], max_length=50),
        ),
    ]
