# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('language', 'Language'), ('framework', 'Framework'), ('platform', 'Platform'), ('library', 'Library'), ('storage', 'Storage Engine'), ('api', 'API'), ('other', 'Other')], default='other', help_text='language - Language,framework - Framework,platform - Platform,library - Library,storage - Storage Engine,api - API,other - Other', max_length=30),
        ),
    ]
