# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-16 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_projects', '0027_interestpoll_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('sender', models.EmailField(blank=True, max_length=254, null=True)),
                ('receiver', models.EmailField(blank=True, max_length=254, null=True)),
                ('emails_in_copy', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunga_projects.Project')),
            ],
        ),
    ]
