# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 09:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_projects', '0027_interestpoll_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tunga_projects.Project'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('estimate', 'Estimate'), ('proposal', 'Proposal'), ('planning', 'Planning'), ('requirements', 'Requirements Document'), ('wireframes', 'Wireframes'), ('timeline', 'Timeline'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='interestpoll',
            name='approval_status',
            field=models.CharField(choices=[('initial', 'Initial'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='initial', help_text='initial - Initial,accepted - Accepted,rejected - Rejected', max_length=20),
        ),
        migrations.AlterField(
            model_name='interestpoll',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_interest_polls_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interestpoll',
            name='status',
            field=models.CharField(choices=[('initial', 'Initial'), ('interested', 'Interested'), ('uninterested', 'Uninterested')], default='initial', help_text='initial - Initial,interested - Interested,uninterested - Uninterested', max_length=20),
        ),
        migrations.AlterField(
            model_name='participation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_participants_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('initial', 'Initial'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='initial', help_text='initial - Initial,accepted - Accepted,rejected - Rejected', max_length=20),
        ),
        migrations.AlterField(
            model_name='progressevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progress_events_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='progressevent',
            name='type',
            field=models.CharField(choices=[('developer', 'Developer Update'), ('pm', 'PM Report'), ('client', 'Client Survey'), ('milestone', 'Milestone'), ('internal', 'Internal Milestone')], default='developer', help_text='developer - Developer Update,pm - PM Report,client - Client Survey,milestone - Milestone,internal - Internal Milestone', max_length=50),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='status',
            field=models.CharField(blank=True, choices=[('on_schedule', 'On schedule'), ('behind', 'Behind'), ('stuck', 'Stuck'), ('behind_progressing', 'Behind but Progressing'), ('behind_stuck', 'Behind and Stuck')], help_text='on_schedule - On schedule,behind - Behind,stuck - Stuck,behind_progressing - Behind but Progressing,behind_stuck - Behind and Stuck', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='stuck_reason',
            field=models.CharField(blank=True, choices=[('resolving_error', 'Resolving an Error'), ('poor_doc', 'Poor Documentation'), ('hardware_problem', 'Hardware problem'), ('unclear_spec', 'Unclear specifications'), ('personal_issue', 'Personal Circumstances'), ('other', 'Other')], help_text='resolving_error - Resolving an Error,poor_doc - Poor Documentation,hardware_problem - Hardware problem,unclear_spec - Unclear specifications,personal_issue - Personal Circumstances,other - Other', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR')], default='EUR', max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='expected_duration',
            field=models.CharField(blank=True, choices=[('2w', '2 Weeks'), ('6m', '6 Months'), ('permanent', 'Permanent')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', initial='PHP, JavaScript, Python, Ruby, Java, C#, C++, Ruby, Swift, Objective C, .NET, ASP.NET, Node.js,HTML, CSS, HTML5, CSS3, XML, JSON, YAML,Django, Ruby on Rails, Flask, Yii, Lavarel, Express.js, Spring, JAX-RS,AngularJS, React.js, Meteor.js, Ember.js, Backbone.js,WordPress, Joomla, Drupal,jQuery, jQuery UI, Bootstrap, AJAX,Android, iOS, Windows Mobile, Apache Cordova, Ionic,SQL, MySQL, PostgreSQL, MongoDB, CouchDB,Git, Subversion, Mercurial, Docker, Ansible, Webpack, Grunt, Gulp, Ant, Maven, Gradle', space_delimiter=False, to='tunga_profiles.Skill'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('opportunity', 'Opportunity'), ('active', 'Active')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
