# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0041_visitors_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appintegration',
            name='provider',
            field=models.CharField(choices=[('slack', 'Slack'), ('harvest', 'Harvest')], help_text='slack - Slack,harvest - Harvest', max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='skills',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', initial='PHP, JavaScript, Python, Ruby, Java, C#, C++, Ruby, Swift, Objective C, .NET, ASP.NET, Node.js,HTML, CSS, HTML5, CSS3, XML, JSON, YAML,Django, Ruby on Rails, Flask, Yii, Lavarel, Express.js, Spring, JAX-RS,AngularJS, React.js, Meteor.js, Ember.js, Backbone.js,WordPress, Joomla, Drupal,jQuery, jQuery UI, Bootstrap, AJAX,Android, iOS, Windows Mobile, Apache Cordova, Ionic,SQL, MySQL, PostgreSQL, MongoDB, CouchDB,Git, Subversion, Mercurial, Docker, Ansible, Webpack, Grunt, Gulp, Ant, Maven, Gradle', space_delimiter=False, to='tunga_profiles.Skill'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.CharField(choices=[('initial', 'Initial'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='initial', help_text='initial - Initial, accepted - Accepted, rejected - Rejected', max_length=30),
        ),
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('language', 'Language'), ('framework', 'Framework'), ('platform', 'Platform'), ('library', 'Library'), ('storage', 'Storage Engine'), ('api', 'API'), ('other', 'Other')], default='other', help_text='language - Language,framework - Framework,platform - Platform,library - Library,storage - Storage Engine,api - API,other - Other', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_money_cc',
            field=models.CharField(blank=True, choices=[('234', 'Nigeria (+234)'), ('255', 'Tanzania (+255)'), ('256', 'Uganda (+256)')], help_text='234 - Nigeria (+234),255 - Tanzania (+255),256 - Uganda (+256)', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', initial='PHP, JavaScript, Python, Ruby, Java, C#, C++, Ruby, Swift, Objective C, .NET, ASP.NET, Node.js,HTML, CSS, HTML5, CSS3, XML, JSON, YAML,Django, Ruby on Rails, Flask, Yii, Lavarel, Express.js, Spring, JAX-RS,AngularJS, React.js, Meteor.js, Ember.js, Backbone.js,WordPress, Joomla, Drupal,jQuery, jQuery UI, Bootstrap, AJAX,Android, iOS, Windows Mobile, Apache Cordova, Ionic,SQL, MySQL, PostgreSQL, MongoDB, CouchDB,Git, Subversion, Mercurial, Docker, Ansible, Webpack, Grunt, Gulp, Ant, Maven, Gradle', space_delimiter=False, to='tunga_profiles.Skill'),
        ),
    ]
