# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-16 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0041_visitors_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitepaperuser',
            name='paper',
            field=models.CharField(choices=[('best_african_countries_for_outsourcing', 'best_african_countries_for_outsourcing'), ('scaling_your_team_with_remote_developers', 'scaling_your_team_with_remote_developers')], default='best_african_countries_for_outsourcing', max_length=255),
            preserve_default=False,
        ),
    ]
