# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0042_auto_20190527_0914'),
        ('tunga_profiles', '0042_whitepaperuser_paper'),
    ]

    operations = [
    ]
